### ISSUE TITLE
ModAssistant (BeatMods) Support

### ISSUE THREAD

**Issue by benniblot** [DJDavid98/bsrpc#6]
Hey, have you thought about uploading your mod to [BeatMods](https://beatmods.com/#/mods) including DiscordCore?

**Comment by DJDavid98** [comment]
I would need to upload both the modified version of DiscordCore and BSDataPuller first as my mod depends on them. I tried to upload the first in the past and I don't think it ever got approved and nobody followed it up with me so I didn't bother trying further.

**Comment by benniblot** [comment]
Are you planning on trying again in the future? It would make it a lot easier to install the mod

**Comment by DJDavid98** [comment]
I'm not actively planning, no.

**Comment by DJDavid98** [comment]
I contacted the BSMG team via Discord and apparently my initial mod submission did not reach their servers for some reason. I have now resubmitted the two dependencies I need on ModAssistant before this mod can be added and got confirmation they saw the submission, I'll keep this issue updated if there's any progress.

**Comment by benniblot** [comment]
Nice, thanks a lot

**Comment by Insprill** [comment]
I see that BeatMods is now hosting your forks of DiscordCore and BSDataPuller, has there been any progress on getting bsrpc uploaded?

**Comment by DJDavid98** [comment]
I was not notified of the mods being approved in any way, I was waiting for that before I would push this mod. The current version was just submitted to BeatMods, hopefully it will eventually also pop up similar to the other two, now we just need to play the waiting game.

**Comment by Insprill** [comment]
bsrpc is now on BeatMods 🥳

**Comment by DJDavid98** [comment]
🎉
